### ISSUE TITLE
[PE-D][Tester D] `add` command clears my `find` results

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#202]
Reproduction:
1. `find ber`
2. `add n/Jing Wen i/E0123456 p/12345678 e/jw@jw.com`
3. Notice my `find` command clears

When using the add command after performing a find, the search results are cleared automatically, disrupting the my workflow. 

This behavior can be confusing and frustrating, as TAs may expect to add new entries without losing their current filtered view of search results. 

Retaining the find results after adding an entry would help TAs manage their data more effectively without needing to re-run the search.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: shotnothing/ped#19

**Comment by Domokunx** [comment]
Reason for resetting after add is because the `find` filter may not be applicable to the newly added contact. 

Unsure how or why `add` and `find` are relevant to each other in a TA context? If the person you tried to find is not there, then you add them. Use case ends.

Similar to https://github.com/AY2425S1-CS2103T-T10-3/tp/issues/187

**Comment by sayglenn** [comment]
Closing this issue as no fix is required.
