### ISSUE TITLE
[PE-D][Tester D] Can't add names with hyphens

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T10-3/tp#230]
Reproduction:
1. `add n/Mary-Ann Lee i/E0123456 p/12345678 e/ns@ns.com`
2. Output: `Names should only contain alphanumeric characters and spaces, and it should not be blank`

This means that if I have any student with this format of name, I am unable to use this app to track them or I have to remove the -, which might cause problems with consistency across apps and NUS's system.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: shotnothing/ped#22

**Comment by Domokunx** [comment]
Agree that some names do have hyphens (I believe such as korean names).

Recommended Fix:
- Mention in planned enhancements?
- Also just double check UG mentions NAME field constraints

Might need more clarification regarding "apps and NUS's system" regarding the context of NUS CS TAs. Maybe they are referring to visually not pleasing that it's not exactly the same?

Due to names being non-unique, schools systems generally use STUDENT_ID instead for identification.

**Comment by sayglenn** [comment]
Hey Cliff, believe there are multiple issues with such behaviour already.
